name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "42 3 * * *"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 5.4
            phpunit: phpunit/phpunit ^4
            can-fail: false
          - php: 5.5
            phpunit: phpunit/phpunit ^4
            can-fail: false
          - php: 5.6
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 7.0
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 7.1
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 7.2
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 7.3
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 7.4
            phpunit: phpunit/phpunit ^5
            can-fail: false
          - php: 8.0
            phpunit: phpunit/phpunit ^9
            can-fail: false
          - php: 8.1
            phpunit: phpunit/phpunit ^9
            can-fail: false
          - php: 8.2
            phpunit: phpunit/phpunit ^9
            can-fail: false

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: "Update PHPUnit version"
        run: composer require --dev --with-all-dependencies --no-install ${{ matrix.phpunit }}

      - name: "Install dependencies"
        run: composer update

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
